In [ ]:
# The goal of this model is to create some datasets and use K Nearest Neighbor Machine learning algorothms to classify the imput data 
# and use accuracy score to identify if the model is predicting accuratly
# The GOAL of this model to predict if Weather and temprature has any decision making ability to play or not play

In [9]:
# Import libraries for the model

import numpy as np
import pandas as pd
import sklearn
from sklearn import datasets, preprocessing
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
# Bellow we will create some feature and label to create our model and to test that model if this predicting properly

# Here we will create to feature weather and tempreture and a label called play

# Creating First Feature

weather=['Sunny','Sunny','Sunny','Overcast','Rainy','Rainy','OverCast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

# Creating Second Feature

temp=['Hot','Hot','Hot','Mild','Cold','Cold','Cold','Mild','Cold','Mild','Mild','Mild','Hot','Mild']
         
# Create Label to identify if player will play based onthe above feature we have weather and temperature

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [66]:
# After createing feature and label we will need to convert those categorial column to numerial column so that Machine Learning Algorith cna understand

# To convert categorial data to numeric ,we will need to use Sklearn label encoder class which is part of preprocessing 

# Bellow creating object from LabelEncoder class

le=preprocessing.LabelEncoder()


# Coverting string features to numeric . For example : Overcast:1, Rainy:2, Sunny:3

weather_encoded=le.fit_transform(weather)

print(weather_encoded)

# Converting Temp column to numeric 

temp_encoded=le.fit_transform(temp)

print(temp_encoded)


# Converting label column to numeric where play:1 and Donot Play:0

label=le.fit_transform(play)

print(label)



[3 3 3 1 2 2 0 3 3 2 3 1 1 2]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [67]:
# Once the columns are converted to numeric data , use zip function to combine both weather and temp column so this works togather to predic if its ok to play or not

combined_feature=list(zip(weather_encoded,temp_encoded))

In [68]:
print(combined_feature) # As we can see variable from each feature column cteated each set so we can put our imput to predcit

[(3, 1), (3, 1), (3, 1), (1, 2), (2, 0), (2, 0), (0, 0), (3, 2), (3, 0), (2, 2), (3, 2), (1, 2), (1, 1), (2, 2)]


In [69]:
# As we discuss , we will be using K Nearest Neighbor algorithm to create our model
# Lets import the class from skleran.neighbors library

from sklearn.neighbors import KNeighborsClassifier

In [70]:
# Once the class is imported ,lets create an object from the class

knn=KNeighborsClassifier(n_neighbors=3)

In [71]:
# Use fit () method to train the model keeping combined feature and lebel inside

knn.fit(combined_feature,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [74]:
# Using trained model to predict the input data for future
# As we have seen when converting string to numeric data :  Overcast:1, Rainy:2, Sunny:3
# Predicting the label AS play:1 and Donot Play:0
predict=knn.predict([[1,2]])
print(predict)

[1]
